// AUTO-GENERATED by failproofai. __failproofai_hook__
// Re-generate via: failproofai policies --install --cli opencode
// Plugin shim that bridges OpenCode's plugin API to the failproofai binary.
// See: https://opencode.ai/docs/plugins/
import { spawnSync } from "node:child_process";

// Map opencode bus-event types → canonical failproofai event names.
// (The binary sees PascalCase — the binary's --cli=opencode flag is for
// telemetry / activity tagging only; no opencode branch in handler.ts.)
const BUS_EVENT_MAP = {
  "session.created": "SessionStart",
  "session.deleted": "SessionEnd",
  "session.idle":    "Stop",
  // message.updated is handled separately (filter to role:user); see below.
};

// Map opencode lowercase tool IDs (`input.tool`) → Claude PascalCase canonical
// names. Builtin failproofai policies match on PascalCase via case-sensitive
// `Array.includes`, so without this every Bash/Read/Write/Edit builtin
// silently no-ops under opencode. Keep in sync with OPENCODE_TOOL_MAP in
// failproofai/src/hooks/types.ts (this shim is loaded in-process by opencode
// and must be self-contained — no imports from the failproofai package).
// Unknown tools pass through unchanged via `?? raw`.
const TOOL_NAME_MAP = {
  bash: "Bash",
  read: "Read",
  write: "Write",
  edit: "Edit",
  apply_patch: "Edit",
  glob: "Glob",
  grep: "Grep",
  list: "LS",
  webfetch: "WebFetch",
  websearch: "WebSearch",
  todowrite: "TodoWrite",
  todoread: "TodoRead",
};
function canonicalizeTool(raw) {
  if (!raw) return raw;
  return TOOL_NAME_MAP[raw] != null ? TOOL_NAME_MAP[raw] : raw;
}

// Per-tool input-key translation: opencode native tools deliver args as
// camelCase (`filePath`, `oldString`, …) but failproofai builtin policies
// (`block-read-outside-cwd`, `block-env-files`, `block-secrets-write`)
// read `ctx.toolInput.file_path` etc. Without this map every Read/Write/Edit
// path-check silently no-ops on opencode. Keys are PascalCase canonical tool
// names so the lookup pairs with canonicalizeTool's output. Tools outside the
// map (MCP `mcp_*`, plugins) pass through unchanged. Keep in sync with
// OPENCODE_TOOL_INPUT_MAP in failproofai/src/hooks/types.ts.
const TOOL_INPUT_MAP = {
  Read: { filePath: "file_path" },
  Write: { filePath: "file_path" },
  Edit: { filePath: "file_path", oldString: "old_string", newString: "new_string", replaceAll: "replace_all" },
};
function canonicalizeToolInput(canonicalToolName, args) {
  if (!args || typeof args !== "object") return args;
  const map = TOOL_INPUT_MAP[canonicalToolName];
  if (!map) return args;
  const out = {};
  for (const k of Object.keys(args)) out[map[k] != null ? map[k] : k] = args[k];
  return out;
}

const FAILPROOFAI_BIN = "";
const USE_NPX = true;

function runFailproofai(eventName, payload, directory) {
  const cmd = USE_NPX ? "npx" : FAILPROOFAI_BIN;
  const args = USE_NPX
    ? ["-y", "failproofai", "--hook", eventName, "--cli", "opencode"]
    : ["--hook", eventName, "--cli", "opencode"];
  const r = spawnSync(cmd, args, {
    input: JSON.stringify(payload),
    encoding: "utf8",
    timeout: 60_000,
    cwd: directory,
  });
  return { exitCode: r.status ?? 0, stdout: r.stdout ?? "", stderr: r.stderr ?? "" };
}

async function applyDecision(result, ctx, eventName) {
  // Deny path 1: exit 2 (Claude Stop-style or any non-Pre/Post deny).
  if (result.exitCode === 2) {
    throw new Error((result.stderr || "").trim() || "Blocked by failproofai");
  }
  // Deny path 2: stdout JSON with hookSpecificOutput.permissionDecision === "deny".
  let parsed = null;
  try { parsed = JSON.parse(result.stdout); } catch { /* fail-open allow */ }
  if (!parsed) return;
  const out = parsed.hookSpecificOutput;
  if (out && out.permissionDecision === "deny") {
    throw new Error(out.permissionDecisionReason || "Blocked by failproofai");
  }
  // Codex-shape PermissionRequest deny: hookSpecificOutput.decision.behavior.
  if (out && out.decision && out.decision.behavior === "deny") {
    throw new Error((out.decision.message) || "Blocked by failproofai");
  }
  // Forward additional context as a prompt to the session. For Stop /
  // SubagentStop the prompt is the only force-retry channel (session.idle
  // already fired), so AWAIT to ensure the SDK round-trip completes before
  // the plugin handler returns. For tool events keep fire-and-forget so we
  // don't add latency to every tool call.
  const ctxText = out && out.additionalContext;
  if (ctxText && ctx && ctx.client && ctx.sessionID) {
    const prompt = ctx.client.session.prompt({
      path: { id: ctx.sessionID },
      body: { parts: [{ type: "text", text: ctxText }] },
    });
    if (eventName === "Stop" || eventName === "SubagentStop") {
      try { await prompt; } catch { /* swallow — agent is exiting anyway */ }
    } else {
      Promise.resolve(prompt).catch(() => {});
    }
  }
}

export default async function failproofaiPlugin({ client, directory }) {
  return {
    // Generic bus events: session lifecycle + user-prompt detection.
    event: async ({ event }) => {
      if (!event || !event.type) return;

      // UserPromptSubmit — filter message.updated to user role only so we
      // don't fire on every assistant token. Forward the prompt text so
      // prompt-based policies (sanitize-* on input, content checks) see it.
      if (event.type === "message.updated") {
        const props = event.properties || {};
        const info = props.info || props.message || {};
        const role = info.role || props.role;
        if (role !== "user") return;
        const sessionID = info.sessionID || info.sessionId || info.session_id || props.sessionID;
        // OpenCode's message shape: parts is an array of {type, text, ...}.
        // Concatenate text parts to reconstruct the user-facing prompt.
        // Fall back to direct text/content fields if a future shape differs.
        let prompt = "";
        const parts = info.parts || props.parts || [];
        if (Array.isArray(parts)) {
          for (const p of parts) {
            if (p && typeof p === "object" && typeof p.text === "string") prompt += p.text;
          }
        }
        if (!prompt) prompt = (info.text || info.content || props.text || "").toString();
        const r = runFailproofai("UserPromptSubmit", {
          session_id: sessionID, cwd: directory, hook_event_name: "UserPromptSubmit", prompt,
        }, directory);
        await applyDecision(r, { client, sessionID }, "UserPromptSubmit");
        return;
      }

      const claudeEvent = BUS_EVENT_MAP[event.type];
      if (!claudeEvent) return;
      const props = event.properties || {};
      const sessionID = props.sessionID || (props.session && props.session.id) || props.id;
      const r = runFailproofai(claudeEvent, {
        session_id: sessionID, cwd: directory, hook_event_name: claudeEvent,
      }, directory);
      await applyDecision(r, { client, sessionID }, claudeEvent);
    },

    // First-class PreToolUse hook. Note: tool args live on output.args (mutable).
    "tool.execute.before": async (input, output) => {
      const canonicalTool = canonicalizeTool(input.tool);
      const r = runFailproofai("PreToolUse", {
        session_id: input.sessionID,
        cwd: directory,
        tool_name: canonicalTool,
        tool_input: canonicalizeToolInput(canonicalTool, output.args),
        hook_event_name: "PreToolUse",
      }, directory);
      await applyDecision(r, { client, sessionID: input.sessionID }, "PreToolUse");
    },

    // First-class PostToolUse hook. Note: tool args live on input.args here.
    "tool.execute.after": async (input, output) => {
      const canonicalTool = canonicalizeTool(input.tool);
      const r = runFailproofai("PostToolUse", {
        session_id: input.sessionID,
        cwd: directory,
        tool_name: canonicalTool,
        tool_input: canonicalizeToolInput(canonicalTool, input.args),
        tool_response: { title: output.title, output: output.output, metadata: output.metadata },
        hook_event_name: "PostToolUse",
      }, directory);
      await applyDecision(r, { client, sessionID: input.sessionID }, "PostToolUse");
    },

    // Cleaner deny UX for prompted tools — mutate output.status instead of throwing.
    "permission.ask": async (input, output) => {
      const canonicalTool = canonicalizeTool(input.tool);
      const r = runFailproofai("PermissionRequest", {
        session_id: input.sessionID,
        cwd: directory,
        tool_name: canonicalTool || input.command || "permission",
        tool_input: canonicalizeToolInput(canonicalTool, input),
        hook_event_name: "PermissionRequest",
      }, directory);
      try {
        await applyDecision(r, { client, sessionID: input.sessionID }, "PermissionRequest");
      } catch {
        output.status = "deny";
      }
    },
  };
}
